
services:
# 3 HTTP Services
# each of them serves an HTML page
# Home Page: http://localhost:8888
  service-home-page:
    #container_name: service-home-page-container
    build:
      context: ./home
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: home/index.js
    ports:
      - 6500:6000
      # the service is listening on 6000
      # the host port is 6500
      # http://localhost:6500

  service-hello:
    #container_name: service-hello-container
    build:
      context: ./hello
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: hello/index.js
    ports:
      - 6100:6000
      # the service is listening on 6000
      # the host port is 6100
      # http://localhost:6100

  service-hey:
    #container_name: service-hey-container
    build:
      context: ./hey
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: hey/index.js
    ports:
      - 6200:6000
      # the service is listening on 6000
      # the host port is 6200
      # http://localhost:6200



# a nginx service (as a reverse proxy)
# this service is using a mounted volume to store it's configuration
  nginx:
      restart: always
      image: nginx:mainline-alpine3.18
      #container_name: nginx
      volumes:
          - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      ports:
        - 8888:80
      # the service is listening on 80
      # the host port is 8888
      # http://localhost:8888

      # http://localhost:8888
      # http://localhost:8888/hello
      # http://localhost:8888/hey

# Prometheus and Grafana services for monitoring
  prometheus:
    image: prom/prometheus:v2.20.1
    #container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090

  grafana:
    image: grafana/grafana:7.1.5
    #container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 4000:3000
    expose:
      - 4000

volumes:
    prometheus_data: {}
    grafana_data: {}
